#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
PREFIX="/usr/local/epson-l120-gutenprint"
PPD="$ROOT/build/Epson_L120-Gutenprint.ppd"

[[ -x "$PREFIX/libexec/cups/filter/rastertogutenprint.5.3" ]] || [[ -x "$PREFIX/lib/cups/filter/rastertogutenprint.5.3" ]] || {
  echo "Gutenprint filter not found. Run ./build.sh first." >&2
  exit 1
}
[[ -f "$PPD" ]] || { echo "PPD not found. Run ./build.sh first." >&2; exit 1; }

FILTER="$PREFIX/libexec/cups/filter/rastertogutenprint.5.3"
[[ -x "$FILTER" ]] || FILTER="$PREFIX/lib/cups/filter/rastertogutenprint.5.3"

cat > "$ROOT/test.txt" <<'TXT'
EPSON L120 GUTENPRINT TEST

Apple Silicon / macOS / CUPS

This page is generated by the actual Gutenprint
Epson L120 (escp2-l120) driver.
TXT

cupsfilter -m application/pdf "$ROOT/test.txt" > "$ROOT/test.pdf"

PPD="$PPD" /usr/libexec/cups/filter/cgpdftoraster \
  1 "$USER" "Epson L120" 1 "" \
  < "$ROOT/test.pdf" > "$ROOT/test.ras"

rm -f "$ROOT/l120-gutenprint-output.bin"

export STP_DATA_PATH="$PREFIX/share/gutenprint/5.3/xml"
export STP_MODULE_PATH="$PREFIX/lib/gutenprint/5.3/modules"

"$FILTER" 1 "$USER" "Epson L120" 1 "" < "$ROOT/test.ras" > "$ROOT/l120-gutenprint-output.bin"

printf '\n=== Results ===\n'
ls -lh "$ROOT/test.pdf" "$ROOT/test.ras" "$ROOT/l120-gutenprint-output.bin"
printf '\nFirst 64 bytes:\n'
xxd -l 64 "$ROOT/l120-gutenprint-output.bin"
printf '\nESC @ occurrences:\n'
grep -aob $'\x1b\x40' "$ROOT/l120-gutenprint-output.bin" | head || true
