#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
VERSION="5.3.5"
SOURCE="$ROOT/work/gutenprint-${VERSION}"
PPD="$ROOT/build/Epson_L120-Gutenprint.ppd"
FILTER="$SOURCE/src/cups/.libs/rastertogutenprint.5.3"
LIBDIR="$SOURCE/src/main/.libs"
XMLDIR="$SOURCE/src/xml"
PDF="$ROOT/test.pdf"
RASTER="$ROOT/test.ras"
OUTPUT="$ROOT/l120-gutenprint-output.bin"

[[ -x "$FILTER" ]] || { echo "ERROR: Gutenprint filter not found. Run ./build.sh first." >&2; exit 1; }
[[ -f "$PPD" ]] || { echo "ERROR: L120 PPD not found. Run ./build.sh first." >&2; exit 1; }
[[ -d "$XMLDIR" ]] || { echo "ERROR: Gutenprint XML data not found. Run ./build.sh first." >&2; exit 1; }

cat > "$ROOT/test.txt" <<'TXT'
EPSON L120 GUTENPRINT TEST

Apple Silicon / macOS / CUPS

This page is generated by the actual Gutenprint
Epson L120 (escp2-l120) driver.
TXT

cupsfilter -m application/pdf "$ROOT/test.txt" > "$PDF"

PPD="$PPD" /usr/libexec/cups/filter/cgpdftoraster \
  1 "${USER:-user}" "Epson L120 Offline Test" 1 "" \
  < "$PDF" > "$RASTER"

rm -f "$OUTPUT"
STP_DATA_PATH="$XMLDIR" \
STP_MODULE_PATH="$LIBDIR:$SOURCE/src/main" \
DYLD_LIBRARY_PATH="$LIBDIR" \
  "$FILTER" 1 "${USER:-user}" "Epson L120 Offline Test" 1 "" \
  < "$RASTER" > "$OUTPUT"

[[ -s "$OUTPUT" ]] || {
  echo "ERROR: Gutenprint produced an empty printer stream." >&2
  exit 1
}

printf '\n=== Offline L120 render passed ===\n'
ls -lh "$PDF" "$RASTER" "$OUTPUT"
printf '\nRenderer:\n'
file "$FILTER"
printf '\nFirst 64 printer bytes:\n'
xxd -l 64 "$OUTPUT"
printf '\nNo printer data was sent over USB.\n'
